#//live
#db.driver: org.postgresql.Driver
#db.url: jdbc:postgresql://34.80.85.203:5432/mvs
#db.username: postgres
#db.password: msp@1234







db.driver: org.postgresql.Driver
db.url: jdbc:postgresql://34.80.85.203:5432/mvs
db.username: mvsuser
db.password: GWiKRZzVdmZBVodf




#//local
#db2.driver: org.postgresql.Driver
#db2.url: jdbc:postgresql://34.80.85.203:5432/mvs
#db2.username: postgres
#db2.password: msp@1234
seckey: eagle@123
