
db.driver: org.postgresql.Driver
db.url: jdbc:postgresql://192.168.1.154:5432/mvs
db.username: postgres
db.password: postgres

db2.driver: org.postgresql.Driver
db2.url: jdbc:postgresql://192.168.1.154:5432/mosip_iderepo
db2.username: postgres
db2.password: postgres

db3.driver: org.postgresql.Driver
db3.url: jdbc:postgresql://192.168.1.154:5432/mosip_regprc
db3.username: postgres
db3.password: postgres



search.filter.max.result : 12


; db.driver: org.postgresql.Driver
; db.url: jdbc:postgresql://34.80.85.203:5432/mvs
; db.username: mvsuser
; db.password: GWiKRZzVdmZBVodf



KERNELAUTHMANAGER : https://api.apps-external.ocp.mspsandbox.com/v1/authmanager/authenticate/clientidsecretkey
appId: regproc
clientId : mosip-regproc-client
secretKey : abc123
IDENTITY : https://api.apps-external.ocp.mspsandbox.com/idrepository/v1/identity/idvid/

case.unassign.time.limit : 20

seckey: eagle@123

KERNELAUTHMANAGERAPI = https://api.apps-external.uat2.phylsys.gov.ph/v1/authmanager/authenticate/clientidsecretkey
BIOAPI = https://packetmanager.apps-external.uat2.phylsys.gov.ph/commons/v1/packetmanager/biometrics
METAINFOAPI = https://packetmanager.apps-external.uat2.phylsys.gov.ph/commons/v1/packetmanager/metaInfo
DOCUMENTAPI = https://packetmanager.apps-external.uat2.phylsys.gov.ph/commons/v1/packetmanager/document
SEARCHFIELDAPI = https://packetmanager.apps-external.uat2.phylsys.gov.ph/commons/v1/packetmanager/searchFields
AUDITAPI = https://packetmanager.apps-external.uat2.phylsys.gov.ph/commons/v1/packetmanager/audits
IDREPOGETAPI = https://api.apps-external.uat2.phylsys.gov.ph/idrepository/v1/identity/idvid/



TokenAppId = regproc
TokenClientId = mosip-regproc-client
TokenRequestSecretKey = abc123

corePoolSize = 10
maximumPoolSize = 10
keepAliveTime = 60

connectTimeout = 60000
socketTimeout = 60000
executorShutdown = 10
priorities=3,2,1
loginAppId = fdms
loginURL = https://api.apps-external.uat2.phylsys.gov.ph/fdms/v1/login/user
loginUsername = kkabilan
loginPassword = Kabi@250598
caseAuthURL = https://api.apps-external.uat2.phylsys.gov.ph/fdms/v1/case/online
