admin.jwt.security.access.token=oEmA76zaE8paVOIpCNaIzBPIPynN85vaJnsf6EnOa2MnCXCpVxR/NanYreSZ4Qrp
admin.jwt.security.access.expiration=86400000
admin.jwt.security.refresh.expiration=604800000
base.context.path = /MVS/
server.servlet.context-path=/MVS
logging.level.com.eagle.mas.* = info
logging.level.root = info
spring.banner.location=static/banner.txt

server.port=9091
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql:true
entitymanager.packagesToScan: com.eagle.mas.model

server.servlet.session.cookie.secure=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
server.error.whitelabel.enabled=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

server.tomcat.relaxed-query-chars=|,{,}
spring.jpa.properties.hibernate.jdbc.batch_size=2000
spring.jpa.properties.hibernate.order_inserts=true

spring.jpa.properties.hibernate.order_updates = true
spring.jpa.hibernate.ddl-auto = update

