# Database
#spring.datasource.driver=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://10.10.10.123:5432/MVS
#spring.datasource.username=postgres
#spring.datasource.password=e@gle@dmin

#spring.datasource.driver=org.postgresql.Driver
#spring.datasource.url=jdbc:postgresql://172.19.3.121:5432/MVS
#spring.datasource.username=postgres
#spring.datasource.password=#phyliOPeTYhiFt123#

server.port=9091
secret=123456789
jwt.secret=yourSecretKey
jwt.expiration=3600000  # Token expiration time in milliseconds (1 hour in this example)
# Hibernate
hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql:true
#hibernate.hbm2ddl.auto: create
entitymanager.packagesToScan:com
#Session Timeou
#server.servlet.session.timeout=3000
server.session.timeout=3000s
server.servlet.session.cookie.max-age=3000s
server.servlet.session.cookie.secure=false
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=128MB
spring.servlet.multipart.max-request-size=128MB
server.error.whitelabel.enabled=false
spring.mvc.hiddenmethod.filter.enabled=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


spring.jpa.properties.hibernate.jdbc.batch_size=2000
spring.jpa.properties.hibernate.order_inserts=true

spring.jpa.properties.hibernate.order_updates=true
