package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AuditLog generated by hbm2java
 */
@Entity
@Table(name = "audit_log")
public class AuditLog implements java.io.Serializable {

	private int id;
	private Integer sno;
	private String userId;
	private String moduleName;
	private Date enteredDate;
	private String enteredBy;
	private String event;
	private String ipAddress;
	private Integer applicantId;
	private String eventDetail;
	public AuditLog() {
	}
	public AuditLog(int id) {
		this.id = id;
	}

	public AuditLog(int id, Integer sno, String userId, String moduleName, Date enteredDate, String enteredBy,
			String event, String ipAddress, Integer applicantId, String eventDetail) {
		this.id = id;
		this.sno = sno;
		this.userId = userId;
		this.moduleName = moduleName;
		this.enteredDate = enteredDate;
		this.enteredBy = enteredBy;
		this.event = event;
		this.ipAddress = ipAddress;
		this.applicantId = applicantId;
		this.eventDetail = eventDetail;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "sno")
	public Integer getSno() {
		return this.sno;
	}

	public void setSno(Integer sno) {
		this.sno = sno;
	}

	@Column(name = "user_id", length = 12)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "module_name", length = 100)
	public String getModuleName() {
		return this.moduleName;
	}

	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entered_date", length = 29)
	public Date getEnteredDate() {
		return this.enteredDate;
	}

	public void setEnteredDate(Date enteredDate) {
		this.enteredDate = enteredDate;
	}

	@Column(name = "entered_by", length = 12)
	public String getEnteredBy() {
		return this.enteredBy;
	}

	public void setEnteredBy(String enteredBy) {
		this.enteredBy = enteredBy;
	}

	@Column(name = "event", length = 500)
	public String getEvent() {
		return this.event;
	}

	public void setEvent(String event) {
		this.event = event;
	}

	@Column(name = "ip_address", length = 50)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "applicant_id")
	public Integer getApplicantId() {
		return this.applicantId;
	}

	public void setApplicantId(Integer applicantId) {
		this.applicantId = applicantId;
	}

	@Column(name = "event_detail")
	public String getEventDetail() {
		return this.eventDetail;
	}

	public void setEventDetail(String eventDetail) {
		this.eventDetail = eventDetail;
	}

}
