package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MstRolegroupToUser generated by hbm2java
 */
@Entity
@Table(name = "mst_rolegroup_to_user")
public class MstRolegroupToUser implements java.io.Serializable {

	private int sno;
	private Userdetails userdetails;
	private Integer roleGroupId;
	private Character activestatus;

	public MstRolegroupToUser() {
	}

	public MstRolegroupToUser(int sno) {
		this.sno = sno;
	}

	public MstRolegroupToUser(int sno, Userdetails userdetails, Integer roleGroupId, Character activestatus) {
		this.sno = sno;
		this.userdetails = userdetails;
		this.roleGroupId = roleGroupId;
		this.activestatus = activestatus;
	}

	@Id

	@Column(name = "sno", unique = true, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public Userdetails getUserdetails() {
		return this.userdetails;
	}

	public void setUserdetails(Userdetails userdetails) {
		this.userdetails = userdetails;
	}

	@Column(name = "role_group_id")
	public Integer getRoleGroupId() {
		return this.roleGroupId;
	}

	public void setRoleGroupId(Integer roleGroupId) {
		this.roleGroupId = roleGroupId;
	}

	@Column(name = "activestatus", length = 1)
	public Character getActivestatus() {
		return this.activestatus;
	}

	public void setActivestatus(Character activestatus) {
		this.activestatus = activestatus;
	}

}
