package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MstRoleToGroup generated by hbm2java
 */
@Entity
@Table(name = "mst_role_to_group")
public class MstRoleToGroup implements java.io.Serializable {

	private int sno;
	private MstRoleGroup mstRoleGroup;
	private MstRoles mstRoles;
	private Character active;

	public MstRoleToGroup() {
	}

	public MstRoleToGroup(int sno) {
		this.sno = sno;
	}

	public MstRoleToGroup(int sno, MstRoleGroup mstRoleGroup, MstRoles mstRoles, Character active) {
		this.sno = sno;
		this.mstRoleGroup = mstRoleGroup;
		this.mstRoles = mstRoles;
		this.active = active;
	}

	@Id

	@Column(name = "sno", unique = true, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "group_id")
	public MstRoleGroup getMstRoleGroup() {
		return this.mstRoleGroup;
	}

	public void setMstRoleGroup(MstRoleGroup mstRoleGroup) {
		this.mstRoleGroup = mstRoleGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public MstRoles getMstRoles() {
		return this.mstRoles;
	}

	public void setMstRoles(MstRoles mstRoles) {
		this.mstRoles = mstRoles;
	}

	@Column(name = "active", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

}
