package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstRoleGroup generated by hbm2java
 */
@Entity
@Table(name = "mst_role_group")
public class MstRoleGroup implements java.io.Serializable {
	private Integer groupId;
	private String groupName;
	private String description;
	private Character activestatus;
	private String enteredBy;
	private Date enteredDate;
	private String modifiedBy;
	private Date modifiedDate;
	private int sno;
	private Set<MstRoleToGroup> mstRoleToGroups = new HashSet<MstRoleToGroup>(0);

	public MstRoleGroup() {
	}

	public MstRoleGroup(Integer groupId, int sno) {
		this.groupId = groupId;
		this.sno = sno;
	}

	public MstRoleGroup(Integer groupId, String groupName, String description, Character activestatus, String enteredBy,
			Date enteredDate, String modifiedBy, Date modifiedDate, int sno, Set<MstRoleToGroup> mstRoleToGroups) {
		this.groupId = groupId;
		this.groupName = groupName;
		this.description = description;
		this.activestatus = activestatus;
		this.enteredBy = enteredBy;
		this.enteredDate = enteredDate;
		this.modifiedBy = modifiedBy;
		this.modifiedDate = modifiedDate;
		this.sno = sno;
		this.mstRoleToGroups = mstRoleToGroups;
	}

	@Id

	@Column(name = "group_id", unique = true, nullable = false)
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "group_name", length = 300)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "activestatus", length = 1)
	public Character getActivestatus() {
		return this.activestatus;
	}

	public void setActivestatus(Character activestatus) {
		this.activestatus = activestatus;
	}

	@Column(name = "entered_by", length = 12)
	public String getEnteredBy() {
		return this.enteredBy;
	}

	public void setEnteredBy(String enteredBy) {
		this.enteredBy = enteredBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entered_date", length = 29)
	public Date getEnteredDate() {
		return this.enteredDate;
	}

	public void setEnteredDate(Date enteredDate) {
		this.enteredDate = enteredDate;
	}

	@Column(name = "modified_by", length = 12)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified_date", length = 29)
	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstRoleGroup")
	public Set<MstRoleToGroup> getMstRoleToGroups() {
		return this.mstRoleToGroups;
	}

	public void setMstRoleToGroups(Set<MstRoleToGroup> mstRoleToGroups) {
		this.mstRoleToGroups = mstRoleToGroups;
	}

}
