package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MstRoles generated by hbm2java
 */
@Entity
@Table(name = "mst_roles")
public class MstRoles implements java.io.Serializable {

	private String roleid;
	private int sno;
	private String roleDetails;
	private String enteredBy;
	private Date enteredDate;
	private String groupName;
	private String roleName;
	private Integer displayOrder;
	private String url;
	private Character active;
	private String icon;
	private String subRoleName;
	private Set<MstRoleToGroup> mstRoleToGroups = new HashSet<MstRoleToGroup>(0);

	public MstRoles() {
	}

	public MstRoles(String roleid, int sno) {
		this.roleid = roleid;
		this.sno = sno;
	}

	public MstRoles(String roleid, int sno, String roleDetails, String enteredBy, Date enteredDate, String groupName,
			String roleName, Integer displayOrder, String url, Character active, String icon, String subRoleName,
			Set<MstRoleToGroup> mstRoleToGroups) {
		this.roleid = roleid;
		this.sno = sno;
		this.roleDetails = roleDetails;
		this.enteredBy = enteredBy;
		this.enteredDate = enteredDate;
		this.groupName = groupName;
		this.roleName = roleName;
		this.displayOrder = displayOrder;
		this.url = url;
		this.active = active;
		this.icon = icon;
		this.subRoleName = subRoleName;
		this.mstRoleToGroups = mstRoleToGroups;
	}

	@Id

	@Column(name = "roleid", unique = true, nullable = false, length = 10)
	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "role_details", length = 100)
	public String getRoleDetails() {
		return this.roleDetails;
	}

	public void setRoleDetails(String roleDetails) {
		this.roleDetails = roleDetails;
	}

	@Column(name = "entered_by", length = 100)
	public String getEnteredBy() {
		return this.enteredBy;
	}

	public void setEnteredBy(String enteredBy) {
		this.enteredBy = enteredBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entered_date", length = 29)
	public Date getEnteredDate() {
		return this.enteredDate;
	}

	public void setEnteredDate(Date enteredDate) {
		this.enteredDate = enteredDate;
	}

	@Column(name = "group_name", length = 50)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "role_name", length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "display_order")
	public Integer getDisplayOrder() {
		return this.displayOrder;
	}

	public void setDisplayOrder(Integer displayOrder) {
		this.displayOrder = displayOrder;
	}

	@Column(name = "url", length = 50)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "active", length = 1)
	public Character getActive() {
		return this.active;
	}

	public void setActive(Character active) {
		this.active = active;
	}

	@Column(name = "icon", length = 50)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "sub_role_name", length = 100)
	public String getSubRoleName() {
		return this.subRoleName;
	}

	public void setSubRoleName(String subRoleName) {
		this.subRoleName = subRoleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mstRoles")
	public Set<MstRoleToGroup> getMstRoleToGroups() {
		return this.mstRoleToGroups;
	}

	public void setMstRoleToGroups(Set<MstRoleToGroup> mstRoleToGroups) {
		this.mstRoleToGroups = mstRoleToGroups;
	}

}
