//
//package com.eagle.mas.model;
//// Generated 22 Jan, 2021 5:52:39 PM by Hibernate Tools 5.4.21.Final
//
//import javax.persistence.*;
//import java.io.Serializable;
//import java.util.Date;
//
///**
// * TblAssigned generated by hbm2java
// */
//@Entity
//@Table(name = "reg_manual_verification")
//public class RegManualVerification implements Serializable {
//
//    private int sno;
//    private String regId;
//    private String matchedRefId;
//    private String matchedRefType;
//    private String statusCode;
//    private String reasonCode;
//    private String updatedBy;
//    private String trntypcode;
//    private String createdBy;
//    private Date updatedDate;
//    private Date createdDate;
//    private String verifyStatus;
//    private String statusComment;
//    private Date updatedDateThree;
//    private String updatedByThree;
//    private String statusCommentThree;
//    private String verifyStatusThree;
//    private String proStatus;
//    private Date updatedDateTwo;
//    private String updatedByTwo;
//    private String statusCommTwo;
//    private String verifyStatusTwo;
//    private String matchingScore;
//
//    public RegManualVerification() {
//
//    }
//
//    public void setSno(int sno) {
//        this.sno = sno;
//    }
//
//
//    @Column(name = "verify_status_two")
//    public String getVerifyStatusTwo() {
//        return verifyStatusTwo;
//    }
//
//    public void setVerifyStatusTwo(String verifyStatusTwo) {
//        this.verifyStatusTwo = verifyStatusTwo;
//    }
//
//
//    @Column(name = "process_status")
//
//    public String getProStatus() {
//        return proStatus;
//    }
//
//    public void setProStatus(String proStatus) {
//        this.proStatus = proStatus;
//    }
//
//    @Column(name = "upd_dt_three")
//    public Date getUpdatedDateThree() {
//        return updatedDateThree;
//    }
//
//
//    public void setUpdatedDateThree(Date updatedDateThree) {
//        this.updatedDateThree = updatedDateThree;
//    }
//
//    //    @OneToOne
//    @Column(name = "status_comment_three")
//    public String getStatusCommentThree() {
//        return statusCommentThree;
//    }
//
//    public void setStatusCommentThree(String statusCommentThree) {
//        this.statusCommentThree = statusCommentThree;
//    }
//
//
//    @Column(name = "upd_by_three")
//    public String getUpdatedByThree() {
//        return updatedByThree;
//    }
//
//    public void setUpdatedByThree(String updatedByThree) {
//        this.updatedByThree = updatedByThree;
//    }
//
//    @Column(name = "verify_status_three")
//    public String getVerifyStatusThree() {
//        return verifyStatusThree;
//    }
//
//    public void setVerifyStatusThree(String verifyStatusThree) {
//        this.verifyStatusThree = verifyStatusThree;
//    }
//
//
//    public void setSno(Integer sno) {
//        this.sno = sno;
//    }
//
//    @Id
//    public Integer getSno() {
//        return sno;
//    }
//
//    @Column(name = "reg_id")
//    public String getRegId() {
//        return regId;
//    }
//
//    public void setRegId(String regId) {
//        this.regId = regId;
//    }
//
//    @Column(name = "matched_ref_id")
//    public String getMatchedRefId() {
//        return matchedRefId;
//    }
//
//    public void setMatchedRefId(String matchedRefId) {
//        this.matchedRefId = matchedRefId;
//    }
//
//    @Column(name = "matched_ref_type")
//    public String getMatchedRefType() {
//        return matchedRefType;
//    }
//
//    public void setMatchedRefType(String matchedRefType) {
//        this.matchedRefType = matchedRefType;
//    }
//
//    @Column(name = "status_code")
//    public String getStatusCode() {
//        return statusCode;
//    }
//
//    public void setStatusCode(String statusCode) {
//        this.statusCode = statusCode;
//    }
//
//    @Column(name = "reason_code")
//    public String getReasonCode() {
//        return reasonCode;
//    }
//
//    public void setReasonCode(String reasonCode) {
//        this.reasonCode = reasonCode;
//    }
//
//    @Column(name = "verify_status")
//    public String getVerifyStatus() {
//        return verifyStatus;
//    }
//
//    public void setVerifyStatus(String verifyStatus) {
//        this.verifyStatus = verifyStatus;
//    }
//
//    @Column(name = "upd_by")
//    public String getUpdatedBy() {
//        return updatedBy;
//    }
//
//    public void setUpdatedBy(String updatedBy) {
//        this.updatedBy = updatedBy;
//    }
//
//    @Column(name = "upd_dtimes")
//    public Date getUpdatedDate() {
//        return updatedDate;
//    }
//
//    public void setUpdatedDate(Date updatedDate) {
//        this.updatedDate = updatedDate;
//    }
//
//    @Column(name = "cr_by")
//    public String getCreatedBy() {
//        return createdBy;
//    }
//
//    public void setCreatedBy(String createdBy) {
//        this.createdBy = createdBy;
//    }
//
//    @Column(name = "cr_dtimes")
//    public Date getCreatedDate() {
//        return createdDate;
//    }
//
//    public void setCreatedDate(Date createdDate) {
//        this.createdDate = createdDate;
//    }
//
//    @Column(name = "trntyp_code")
//    public String getTrntypcode() {
//        return trntypcode;
//    }
//
//    public void setTrntypcode(String trntypcode) {
//        this.trntypcode = trntypcode;
//    }
//
//    @Column(name = "matched_score")
//    public String getMatchingScore() {
//        return matchingScore;
//    }
//
//    public void setMatchingScore(String matchingScore) {
//        this.matchingScore = matchingScore;
//    }
//
//    @Column(name = "status_comment")
//    public String getStatusComment() {
//        return statusComment;
//    }
//
//    public void setStatusComment(String statusComment) {
//        this.statusComment = statusComment;
//    }
//
//    @Column(name = "upd_dt_two")
//    public Date getUpdatedDateTwo() {
//        return updatedDateTwo;
//    }
//
//    public void setUpdatedDateTwo(Date updatedDateTwo) {
//        this.updatedDateTwo = updatedDateTwo;
//    }
//
//    @Column(name = "upd_by_two")
//    public String getUpdatedByTwo() {
//        return updatedByTwo;
//    }
//
//    public void setUpdatedByTwo(String updatedByTwo) {
//        this.updatedByTwo = updatedByTwo;
//    }
//
//
////@Column(name="user1")
////    public String getUser1() {
////        return user1;
////    }
////
////    public void setUser1(String user1) {
////        this.user1 = user1;
////    }
////    @Column(name="user2")
////    public String getUser2() {
////        return user2;
////    }
////
////    public void setUser2(String user2) {
////        this.user2 = user2;
////    }
////    @Column(name="flagstatus")
////    public String getFlagstatus() {
////        return flagstatus;
////    }
////
////    public void setFlagstatus(String flagstatus) {
////        this.flagstatus = flagstatus;
////    }
//
//    @Column(name = "status_comment_two")
//    public String getStatusCommTwo() {
//        return statusCommTwo;
//    }
//
//    public void setStatusCommTwo(String statusCommTwo) {
//        this.statusCommTwo = statusCommTwo;
//    }
//
//
////    public String getOper1Comm() {
////        return oper1Comm;
////    }
////
////    public void setOper1Comm(String oper1Comm) {
////        this.oper1Comm = oper1Comm;
////    }
////
////    public String getOper2Comm() {
////        return oper2Comm;
////    }
////
////    public void setOper2Comm(String oper2Comm) {
////        this.oper2Comm = oper2Comm;
////    }
//
////    @Column(name="oper1_comm")
////    private String oper1Comm;
////
////    @Column(name="oper2_comm")
////    private String oper2Comm;
////    private String user1;
////    private String user2;
////    private String flagstatus;
//}
