package com.eagle.mas.model;
// Generated 22 Jan, 2021 5:52:39 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblAssigned generated by hbm2java
 */
@Entity
@Table(name = "tbl_assigned")
public class TblAssigned implements java.io.Serializable {

	private int sno;
	private String assignedUserId;
	private Date assignedDate;
	private String gallery;
	private String rid;

	public TblAssigned() {
	}

	public TblAssigned(int sno) {
		this.sno = sno;
	}

	public TblAssigned(int sno, String assignedUserId, Date assignedDate, String gallery, String rid) {
		this.sno = sno;
		this.assignedUserId = assignedUserId;
		this.assignedDate = assignedDate;
		this.gallery = gallery;
		this.rid = rid;
	}

	@Id
	@Column(name = "sno", unique = true, nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "assigned_user_id")
	public String getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(String assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	@Column(name = "assigned_date")
	public Date getAssignedDate() {
		return this.assignedDate;
	}

	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}

	@Column(name = "gallery")
	public String getGallery() {
		return this.gallery;
	}

	public void setGallery(String gallery) {
		this.gallery = gallery;
	}

	@Column(name = "rid")
	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

}
