package com.eagle.mas.model;
// Generated 28 Nov, 2020 7:00:24 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userdetails generated by hbm2java
 */
@Entity
@Table(name = "userdetails")
public class Userdetails implements java.io.Serializable {

	private String userid;
private String UserApproval;
	private int sno;
	private String password;
	private String firstnameEn;
	private String middleName;
	private String lastnameEn;
	private String contactnumber;
	private char activestatus;
	private String belongsTo;
	private String enteredBy;
	private Date enteredDate;
	private String email;	
	private String loginStatus;
	private String designation;
//	private String department;
	private String organisation;
//	private String mobileNo;
	private String verifycodePwd;
//	private Integer title;
	private Character isloggedin;
	private Date loginTime;
	private Date logoutTime;
	private String loginFrom;

	private Set<MstRolegroupToUser> mstRolegroupToUsers = new HashSet<MstRolegroupToUser>(0);

	public Userdetails() {
	}

	public Userdetails(String userid, int sno, char activestatus) {
		this.userid = userid;
		this.sno = sno;
		this.activestatus = activestatus;
	}

	public Userdetails(String userid, String UserApproval, int sno, String password,
			String firstnameEn, String middleName, String lastnameEn, String contactnumber, char activestatus,
			String belongsTo, String enteredBy, Date enteredDate, String email,  
		  String loginStatus, String designation,
			String organisation, String verifycodePwd,  Character isloggedin,
			Date loginTime, Date logoutTime, String loginFrom,
			Set<MstRolegroupToUser> mstRolegroupToUsers) {
		
		this.userid = userid;
		this.UserApproval=UserApproval;
		this.sno = sno;
		this.password = password;
		this.firstnameEn = firstnameEn;
		this.middleName = middleName;
		this.lastnameEn = lastnameEn;
		this.contactnumber = contactnumber;
		this.activestatus = activestatus;
		this.belongsTo = belongsTo;
		this.enteredBy = enteredBy;
		this.enteredDate = enteredDate;
		this.email = email;
		this.loginStatus = loginStatus;
		this.designation = designation;
//		this.department = department;
		this.organisation = organisation;
//		this.mobileNo = mobileNo;
		this.verifycodePwd = verifycodePwd;
//		this.title = title;
		this.isloggedin = isloggedin;
		this.loginTime = loginTime;
		this.logoutTime = logoutTime;
		this.loginFrom = loginFrom;
		
		this.mstRolegroupToUsers = mstRolegroupToUsers;
	}

	@Id

	@Column(name = "userid", unique = true, nullable = false, length = 12)
	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}
	@Column(name = "user_approval")
	public String getUserApproval() {
		return UserApproval;
	}

	public void setUserApproval(String userApproval) {
		UserApproval = userApproval;
	}

	@Column(name = "sno", nullable = false)
	public int getSno() {
		return this.sno;
	}

	public void setSno(int sno) {
		this.sno = sno;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname_en", length = 100)
	public String getFirstnameEn() {
		return this.firstnameEn;
	}

	public void setFirstnameEn(String firstnameEn) {
		this.firstnameEn = firstnameEn;
	}

	@Column(name = "middle_name", length = 100)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "lastname_en", length = 100)
	public String getLastnameEn() {
		return this.lastnameEn;
	}

	public void setLastnameEn(String lastnameEn) {
		this.lastnameEn = lastnameEn;
	}

	@Column(name = "contactnumber", length = 20)
	public String getContactnumber() {
		return this.contactnumber;
	}

	public void setContactnumber(String contactnumber) {
		this.contactnumber = contactnumber;
	}

	@Column(name = "activestatus", nullable = false, length = 1)
	public char getActivestatus() {
		return this.activestatus;
	}

	public void setActivestatus(char activestatus) {
		this.activestatus = activestatus;
	}

	@Column(name = "belongs_to", length = 50)
	public String getBelongsTo() {
		return this.belongsTo;
	}

	public void setBelongsTo(String belongsTo) {
		this.belongsTo = belongsTo;
	}

	@Column(name = "entered_by", length = 12)
	public String getEnteredBy() {
		return this.enteredBy;
	}

	public void setEnteredBy(String enteredBy) {
		this.enteredBy = enteredBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "entered_date", length = 29)
	public Date getEnteredDate() {
		return this.enteredDate;
	}

	public void setEnteredDate(Date enteredDate) {
		this.enteredDate = enteredDate;
	}

	

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "login_status", length = 50)
	public String getLoginStatus() {
		return this.loginStatus;
	}

	public void setLoginStatus(String loginStatus) {
		this.loginStatus = loginStatus;
	}

	@Column(name = "designation", length = 100)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

//	@Column(name = "department", length = 100)
//	public String getDepartment() {
//		return this.department;
//	}
//
//	public void setDepartment(String department) {
//		this.department = department;
//	}

	@Column(name = "organisation", length = 300)
	public String getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

//	@Column(name = "mobile_no", length = 50)
//	public String getMobileNo() {
//		return this.mobileNo;
//	}
//
//	public void setMobileNo(String mobileNo) {
//		this.mobileNo = mobileNo;
//	}

	@Column(name = "verifycode_pwd", length = 100)
	public String getVerifycodePwd() {
		return this.verifycodePwd;
	}

	public void setVerifycodePwd(String verifycodePwd) {
		this.verifycodePwd = verifycodePwd;
	}
//
//	@Column(name = "title")
//	public Integer getTitle() {
//		return this.title;
//	}
//
//	public void setTitle(Integer title) {
//		this.title = title;
//	}

	@Column(name = "isloggedin", length = 1)
	public Character getIsloggedin() {
		return this.isloggedin;
	}

	public void setIsloggedin(Character isloggedin) {
		this.isloggedin = isloggedin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "login_time", length = 29)
	public Date getLoginTime() {
		return this.loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "logout_time", length = 29)
	public Date getLogoutTime() {
		return this.logoutTime;
	}

	public void setLogoutTime(Date logoutTime) {
		this.logoutTime = logoutTime;
	}

	@Column(name = "login_from", length = 100)
	public String getLoginFrom() {
		return this.loginFrom;
	}

	public void setLoginFrom(String loginFrom) {
		this.loginFrom = loginFrom;
	}

	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userdetails")
	public Set<MstRolegroupToUser> getMstRolegroupToUsers() {
		return this.mstRolegroupToUsers;
	}

	public void setMstRolegroupToUsers(Set<MstRolegroupToUser> mstRolegroupToUsers) {
		this.mstRolegroupToUsers = mstRolegroupToUsers;
	}

}
