Mail.Server =mail.philsys.gov.ph
Mail.Port =587
Mail.From =register@philsys.gov.ph
Mail.User =register@philsys.gov.ph
Mail.Password =42DxfhnVe2
# Mail.Server =192.168.1.10
# Mail.Port =25
# Mail.From =test@eagle.com
# Mail.User =appdev
# Mail.Password =!@#esilapp@2020#@!